# Generated by Django 4.0.5 on 2022-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='update_at')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('feels_like', models.CharField(blank=True, max_length=255, null=True)),
                ('wind', models.CharField(blank=True, max_length=255, null=True)),
                ('pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('humidity', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alerts', models.CharField(blank=True, max_length=255, null=True)),
                ('events', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
