# Generated by Django 4.0.5 on 2022-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
