# Generated by Django 4.0.5 on 2022-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_alter_forecast_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
