# Generated by Django 4.0.5 on 2022-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_alter_forecast_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='alerts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
